force-app/main/default/objects/Block__mdt/Block__mdt.object-meta.xml
<CustomObject>
    <label>Block</label>
    <pluralLabel>Blocks</pluralLabel>
</CustomObject>

force-app/main/default/objects/Block__mdt/fields/Block_Id__c.field-meta.xml
<CustomField>
    <fullName>Block_Id__c</fullName>
    <label>Block Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Block__mdt/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <referenceTo>Floor__mdt</referenceTo>
    <relationshipLabel>Blocks</relationshipLabel>
    <relationshipName>Blocks</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Building__mdt/Building__mdt.object-meta.xml
<CustomObject>
    <label>Building</label>
    <pluralLabel>Buildings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Building__mdt/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Locations__mdt</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Cubicle__mdt/Cubicle__mdt.object-meta.xml
<CustomObject>
    <label>Cubicle</label>
    <pluralLabel>Cubicles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cubicle__mdt/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <label>Block</label>
    <referenceTo>Block__mdt</referenceTo>
    <relationshipLabel>Cubicles</relationshipLabel>
    <relationshipName>Cubicles</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Cubicle__mdt/fields/Cubicle_Id__c.field-meta.xml
<CustomField>
    <fullName>Cubicle_Id__c</fullName>
    <label>Cubicle Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cubicle__mdt/fields/entry__c.field-meta.xml
<CustomField>
    <fullName>entry__c</fullName>
    <label>entry</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>leftentry</fullName>
                <default>true</default>
                <label>leftentry</label>
            </value>
            <value>
                <fullName>topentry</fullName>
            </value>
            <value>
                <fullName>rightentry</fullName>
            </value>
            <value>
                <fullName>bottomentry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Floor__mdt/Floor__mdt.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <pluralLabel>Floors</pluralLabel>
</CustomObject>

force-app/main/default/objects/Floor__mdt/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__mdt</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Locations__mdt/Locations__mdt.object-meta.xml
<CustomObject>
    <label>Location</label>
    <pluralLabel>Locations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Preferences__mdt/Preferences__mdt.object-meta.xml
<CustomObject>
    <label>Preferences</label>
    <pluralLabel>Preferences</pluralLabel>
</CustomObject>

force-app/main/default/objects/Seat__mdt/Seat__mdt.object-meta.xml
<CustomObject>
    <label>Seat</label>
    <pluralLabel>Seats</pluralLabel>
</CustomObject>

force-app/main/default/objects/Seat__mdt/fields/Cubicle__c.field-meta.xml
<CustomField>
    <fullName>Cubicle__c</fullName>
    <label>Cubicle</label>
    <referenceTo>Cubicle__mdt</referenceTo>
    <relationshipLabel>Seats</relationshipLabel>
    <relationshipName>Seats</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Seat__mdt/fields/IsCloseToAC__c.field-meta.xml
<CustomField>
    <fullName>IsCloseToAC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCloseToAC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seat__mdt/fields/isCloseToDoor__c.field-meta.xml
<CustomField>
    <fullName>isCloseToDoor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCloseToDoor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seat__mdt/fields/isCloseToMeetingRoom__c.field-meta.xml
<CustomField>
    <fullName>isCloseToMeetingRoom__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCloseToMeetingRoom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seat__mdt/fields/isCloseToWIndow__c.field-meta.xml
<CustomField>
    <fullName>isCloseToWIndow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCloseToWIndow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seat__mdt/fields/Seat_Id__c.field-meta.xml
<CustomField>
    <fullName>Seat_Id__c</fullName>
    <label>Seat Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SeatSelectorController.cls
public inherited sharing class SeatSelectorController {
    public SeatSelectorController() {

    }

    @AuraEnabled(cacheable=true)
    public static String fetchConfiguration() {
        ConfigWrapper configWrap = new ConfigWrapper();
        List<Locations__mdt> locations = [select label from Locations__mdt];
        List<Building__mdt> buildings = [select label,Location__r.DeveloperName from Building__mdt];
        List<Floor__mdt> floors = [select label,Building__r.DeveloperName from Floor__mdt];
        List<Preferences__mdt> preferences = [select label from Preferences__mdt];

        List<Block__mdt> blocks = [select label,Block_Id__c,Floor__r.DeveloperName from Block__mdt];
        List<Cubicle__mdt> cubicles = [select label,Block__r.DeveloperName,Cubicle_Id__c,entry__c from Cubicle__mdt];
        List<Seat__mdt> seats = [select label,Cubicle__r.DeveloperName,IsCloseToAC__c,isCloseToDoor__c,
                                isCloseToMeetingRoom__c,isCloseToWIndow__c,Seat_Id__c from Seat__mdt];

        configWrap.buildings = new List<ConfigWrapper.buildingWrapper>();
        for(Building__mdt building: buildings){
            ConfigWrapper.buildingWrapper buildingData = new ConfigWrapper.buildingWrapper();
            buildingData.building = building.label;
            buildingData.location = building.Location__r.DeveloperName;
            configWrap.buildings.add(buildingData);
        }

        configWrap.locations = new List<ConfigWrapper.locationWrapper>();
        for(Locations__mdt location: locations){
            ConfigWrapper.locationWrapper locationData = new ConfigWrapper.locationWrapper();
            locationData.location = location.label;
            configWrap.locations.add(locationData);
        }

        configWrap.floors = new List<ConfigWrapper.floorWrapper>();
        for(Floor__mdt floor: floors){
            ConfigWrapper.floorWrapper floorData = new ConfigWrapper.floorWrapper();
            floorData.floorName = floor.label;
            floorData.building = floor.Building__r.DeveloperName;
            configWrap.floors.add(floorData);
        }

        configWrap.Preferences = new List<ConfigWrapper.PreferenceWrapper>();
        for(Preferences__mdt preference: preferences){
            ConfigWrapper.PreferenceWrapper PreferenceData = new ConfigWrapper.PreferenceWrapper();
            PreferenceData.preference = preference.label;
            configWrap.Preferences.add(PreferenceData);
        }

        configWrap.blocks = new List<ConfigWrapper.blockWrapper>();
        for(Block__mdt block: blocks){
            ConfigWrapper.blockWrapper blockData = new ConfigWrapper.blockWrapper();
            blockData.blockName = block.label;
            blockData.blockId = block.Block_Id__c;
            blockData.floor = block.Floor__r.DeveloperName;
            configWrap.blocks.add(blockData);
        }

        configWrap.cubicles = new List<ConfigWrapper.cubicleWrapper>();
        for(Cubicle__mdt cubicle: cubicles){
            ConfigWrapper.cubicleWrapper cubicleData = new ConfigWrapper.cubicleWrapper();
            cubicleData.cubicleId = cubicle.Cubicle_Id__c;
            cubicleData.cubicleName = cubicle.label;
            cubicleData.block = cubicle.Block__r.DeveloperName;
            cubicleData.entry = cubicle.entry__c;
            configWrap.cubicles.add(cubicleData);
        }

        configWrap.seats = new List<ConfigWrapper.seatWrapper>();
        for(Seat__mdt seat: seats){
            ConfigWrapper.seatWrapper seatData = new ConfigWrapper.seatWrapper();
            seatData.seatId = seat.Seat_Id__c;
            seatData.seatName = seat.label;
            seatData.cubicle = seat.Cubicle__r.DeveloperName;
            seatData.isCloseToAC = seat.IsCloseToAC__c;
            seatData.isCloseToDoor = seat.isCloseToDoor__c;
            seatData.isCloseToMeetingRoom = seat.isCloseToMeetingRoom__c;
            seatData.isCloseToWindow = seat.isCloseToWIndow__c;
            configWrap.seats.add(seatData);
        }

        return JSON.serialize(configWrap);
    }

    @AuraEnabled
    public static List < Map < String, String >> getPreferenceValues(){
        List<Preferences__mdt> preferences = [select label from Preferences__mdt];
        List < Map < String, String >> options = new List < Map < String, String >> ();
        for(Preferences__mdt preference: preferences){
            Map < String, String > values = new Map < String, String > {
                'key' => preference.label,
                'value' => preference.label
            };
            options.add(values);
        }
        return options;
    }
    
}