force-app/main/default/objects/Seat_Information__c/Seat_Information__c.object-meta.xml
<CustomObject>
    <label>Seat Information</label>
    <nameField>
        <label>Seat Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seat Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Information__c/fields/Last_Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Booked_Date__c</fullName>
    <description>Last Date the seat was booked</description>
    <inlineHelpText>Last Date the seat was booked</inlineHelpText>
    <label>Last Booked Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SeatInformationAnalysis.cls
@RestResource(urlMapping='/SeatInformation/*')
global without sharing class SeatInformationAnalysis {
    
    @HttpGet
    global static String getBasicSeatInformationInfo() {
        RestRequest request = RestContext.request;
        // grab the caseId from the end of the URL
        String seatId = request.requestURI.substring(
          request.requestURI.lastIndexOf('/')+1);
        Seat_Information__c result =  [SELECT Id, Last_Booked_Date__c, Name 
                        FROM Seat_Information__c where Name=:seatId];
        
        return result.Last_Booked_Date__c == null ? null : String.valueOf(result.Last_Booked_Date__c);
    }

}