force-app/main/default/objects/APIvsCalloutInformation__mdt/APIvsCalloutInformation__mdt.object-meta.xml
<CustomObject>
    <label>APIvsCalloutInformation</label>
    <pluralLabel>APIvsCalloutInformations</pluralLabel>
</CustomObject>

force-app/main/default/objects/APIvsCalloutInformation__mdt/fields/Http_Method_Type__c.field-meta.xml
<CustomField>
    <fullName>Http_Method_Type__c</fullName>
    <label>Http Method Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SeatInformationCalloutRequestor.cls
public class SeatInformationCalloutRequestor {
    static Map<String,APIvsCalloutInformation__mdt> apiVsCalloutInformation = new Map<String,APIvsCalloutInformation__mdt>();
    static{
        for(APIvsCalloutInformation__mdt apiInfo: [select Label,DeveloperName,Endpoint_Name__c,Http_Method_Type__c from 
                                                      APIvsCalloutInformation__mdt]){
            apiVsCalloutInformation.put(apiInfo.DeveloperName,apiInfo);
        }
        
    }
    
    public static String callSeatBookingAPI(Map<String,String> seatBookingData){
        Http http = new Http();
        HttpRequest request = getBasicRequestInfo('Booking',seatBookingData);
        String apiRequestBody = getBookingApiRequest(seatBookingData);
        request.setBody(apiRequestBody);
        HttpResponse response = http.send(request);
        System.debug('resp body ---->'+response.getBody());
        if (response.getStatusCode() == 200) {
            
            return SeatInformationUtility.upsertBookedSeatInformation(RestContext.request.requestBody.toString());
        }
        return 'Something went wrong.. Hold Tight!!';
    }
    private static HttpRequest getBasicRequestInfo(String apiName,Map<String,String> seatBookingData){
        APIvsCalloutInformation__mdt apiMetaInfo = apiVsCalloutInformation.get(apiName);
        HttpRequest request = new HttpRequest();
        String url = apiMetaInfo.Endpoint_Name__c;
        for(String key: seatBookingData.keySet()){
            url = url.replace('{'+key+'}', seatBookingData.get(key));
        }
		request.setEndpoint(url);
        System.debug('url ----> '+url);
		request.setMethod('POST');
		request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        return request;
    }
    
    private static String getBookingApiRequest(Map<String,String> seatBookingData){
        SeatInformationBookingWrapper seatBookWrapper = new SeatInformationBookingWrapper();
        return seatBookWrapper.getRequestBody(seatBookingData); 
    }

}