force-app/main/default/objects/Blocks__c/Blocks__c.object-meta.xml
<CustomObject>
    <label>Block</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Block Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Blocks__c/fields/Block_Id__c.field-meta.xml
<CustomField>
    <fullName>Block_Id__c</fullName>
    <label>Block Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Blocks__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <referenceTo>Floors__c</referenceTo>
    <relationshipLabel>Blocks</relationshipLabel>
    <relationshipName>Blocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Blocks__c/fields/isMeetingRoom__c.field-meta.xml
<CustomField>
    <fullName>isMeetingRoom__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isMeetingRoom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Blocks__c/fields/IsWindow__c.field-meta.xml
<CustomField>
    <fullName>IsWindow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsWindow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Blocks__c/fields/Meeting_Room__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Room__c</fullName>
    <label>Meeting Room</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blocks__c/fields/Window__c.field-meta.xml
<CustomField>
    <fullName>Window__c</fullName>
    <label>Window</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Buildings__c/Buildings__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Buildings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Buildings__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Buildings</relationshipLabel>
    <relationshipName>Buildings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cubicles__c/Cubicles__c.object-meta.xml
<CustomObject>
    <label>Cubicle</label>
    <nameField>
        <displayFormat>CU-{0000}</displayFormat>
        <label>Cubicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cubicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cubicles__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Block</label>
    <referenceTo>Blocks__c</referenceTo>
    <relationshipLabel>Cubicles</relationshipLabel>
    <relationshipName>Cubicles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cubicles__c/fields/Cubicle_Id__c.field-meta.xml
<CustomField>
    <fullName>Cubicle_Id__c</fullName>
    <label>Cubicle Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cubicles__c/fields/entry__c.field-meta.xml
<CustomField>
    <fullName>entry__c</fullName>
    <label>entry</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>bottomentry</fullName>
            </value>
            <value>
                <fullName>leftentry</fullName>
            </value>
            <value>
                <fullName>rightentry</fullName>
            </value>
            <value>
                <fullName>topentry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Floors__c/Floors__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Floor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Floors__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Buildings__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seats__c/Seats__c.object-meta.xml
<CustomObject>
    <label>Seat</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Seat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seats__c/fields/Cubicle__c.field-meta.xml
<CustomField>
    <fullName>Cubicle__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cubicle</label>
    <referenceTo>Cubicles__c</referenceTo>
    <relationshipLabel>Seats</relationshipLabel>
    <relationshipName>Seats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seats__c/fields/IsCloseToAC__c.field-meta.xml
<CustomField>
    <fullName>IsCloseToAC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCloseToAC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seats__c/fields/isCloseToDoor__c.field-meta.xml
<CustomField>
    <fullName>isCloseToDoor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCloseToDoor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seats__c/fields/isCloseToMeetingRoom__c.field-meta.xml
<CustomField>
    <fullName>isCloseToMeetingRoom__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCloseToMeetingRoom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seats__c/fields/isCloseToWIndow__c.field-meta.xml
<CustomField>
    <fullName>isCloseToWIndow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCloseToWIndow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seats__c/fields/Seat_id__c.field-meta.xml
<CustomField>
    <fullName>Seat_id__c</fullName>
    <label>Seat id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SeatSelectorControllerTest.cls
@isTest
public class SeatSelectorControllerTest{
    @testsetup static void init_Data(){
        Location__c location = new Location__c();
        location.Name__c = 'Nagpur';
        insert location;
        
        Buildings__c building = new Buildings__c();
        building.Name__c = 'Gargee';
        building.Location__c = location.id;
        insert building;
        
        Floors__c floor = new Floors__c();
        floor.Name__c = 'G0';
        floor.Building__c = building.id;
        floor.Columns__c = 3;
        insert floor;
        
        Blocks__c block = new Blocks__c();
        block.Block_Id__c = '12345';
        block.Floor__c = floor.id;
        block.isMeetingRoom__c = true;
        block.IsWindow__c = true;
        block.Meeting_Room__c = '';
        block.Window__c = 'left';
        insert block;
        
        Cubicles__c cubicle = new Cubicles__c();
        cubicle.Block__c = block.id;
        cubicle.Cubicle_Id__c = '12345';
        cubicle.entry__c = 'bottomentry';
        insert cubicle;
        
        Seats__c seat = new Seats__c();
        seat.Cubicle__c = cubicle.id;
        seat.IsCloseToAC__c = true;
        seat.isCloseToDoor__c = true;
        seat.isCloseToMeetingRoom__c = true;
        seat.isCloseToWIndow__c = true;
        seat.Seat_Id__c = '123';
        insert seat;
    }

    @isTest 
    static void test_fetchConfiguration(){
        List<Buildings__c> buildings = [select Name__c,Location__r.Name__c from Buildings__c];
        List<Floors__c> floors = [select Name__c,Building__r.Name__c,Columns__c from Floors__c];
        List<Blocks__c> blocks = [select Block_Id__c,Floor__r.Name__c,isMeetingRoom__c,IsWindow__c,
                                    Meeting_Room__c,Window__c from Blocks__c order by Block_Id__c];
        List<Cubicles__c> cubicles = [select Block__r.Block_Id__c,Cubicle_Id__c,entry__c from Cubicles__c order by Cubicle_Id__c];
        List<Seats__c> seats = [select Cubicle__r.Cubicle_Id__c,IsCloseToAC__c,isCloseToDoor__c,
                                isCloseToMeetingRoom__c,isCloseToWIndow__c,Seat_Id__c from Seats__c];
        
        Test.startTest();
            SeatSelectorController.fetchConfiguration();
        Test.stopTest();
    }
    
    @isTest 
    static void test_getPreferenceValues(){
        Test.startTest();
        	SeatSelectorController seat = new SeatSelectorController();
            SeatSelectorController.getPreferenceValues();
        Test.stopTest();
    }
    
    @isTest 
    static void test_loginUser(){
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
            SeatSelectorController.loginUser('12345');
        Test.stopTest();
    }
    
    @isTest 
    static void test_bookSeat(){
        Map<String,String> bookingDetail = new Map<String,String>();
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
            SeatSelectorController.bookSeat(bookingDetail);
        Test.stopTest();
    }
    
    @isTest 
    static void test_returnSeat(){
        Map<String,String> bookingDetail = new Map<String,String>();
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
            SeatSelectorController.returnSeat(bookingDetail);
        	SeatSelectorController.getFeedback('1234');
        Test.stopTest();
    }
    
    @isTest 
    static void test_getAllBookedSeats(){
        Map<String,String> bookingDetail = new Map<String,String>();
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
            SeatSelectorController.getAllBookedSeats(bookingDetail);
        Test.stopTest();
    }
    
    @isTest 
    static void test_getMyBookedSeats(){
        Map<String,String> bookingDetail = new Map<String,String>();
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
            SeatSelectorController.getMyBookedSeats(bookingDetail);
        Test.stopTest();
    }
    
    @isTest 
    static void test_occupySeat(){
        Map<String,String> bookingDetail = new Map<String,String>();
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
            SeatSelectorController.occupySeat(bookingDetail);
        Test.stopTest();
    }
    
    private class RestMock implements HttpCalloutMock{
        public HTTPResponse respond(HTTPRequest req){
            String fullJson = 'your Json Response';
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }

}